package core.game.system.command.sets

const val STATS_BASE = "stats_manager"
const val STATS_ENEMIES_KILLED = "enemies_killed"
const val STATS_DEATHS = "deaths"
const val STATS_LOGS = "logs_chopped"
const val STATS_FISH = "fish_caught"
const val STATS_ROCKS = "rocks_mined"
const val STATS_RC = "essence_crafted"
const val STATS_FOOD_COOKED = "food_cooked"
const val STATS_CATS_RAISED = "cats_raised"
const val STATS_PK_KILLS = "player_kills"
const val STATS_PK_DEATHS = "player_deaths"
const val STATS_DAMAGE_DEALT_TOTAL = "damage_dealt_total"
const val STATS_DAMAGE_DEALT_MELEE = "damage_dealt_melee"
const val STATS_DAMAGE_DEALT_RANGE = "damage_dealt_range"
const val STATS_DAMAGE_DEALT_MAGIC = "damage_dealt_magic"
const val STATS_HIGHEST_HIT_TOTAL = "highest_hit_total"
const val STATS_HIGHEST_HIT_MELEE = "highest_hit_melee"
const val STATS_HIGHEST_HIT_RANGE = "highest_hit_range"
const val STATS_HIGHEST_HIT_MAGIC = "highest_hit_magic"
const val STATS_ALKHARID_GATE = "alkharid_gate"
const val FISHING_TRAWLER_GAMES_WON = "fishing-trawler-games"
const val FISHING_TRAWLER_LEAKS_PATCHED = "fishing-trawler-leaks-patched"
const val FISHING_TRAWLER_SHIPS_SANK = "fishing-trawler-sank"
